// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: data.proto

package data

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Data_UploadVideo_FullMethodName               = "/video.Data/UploadVideo"
	Data_EstablishUploadConnection_FullMethodName = "/video.Data/EstablishUploadConnection"
	Data_DownloadVideo_FullMethodName             = "/video.Data/DownloadVideo"
)

// DataClient is the client API for Data service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataClient interface {
	UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VideoChunk, UploadStatus], error)
	EstablishUploadConnection(ctx context.Context, in *VideoUploadData, opts ...grpc.CallOption) (*UploadStatus, error)
	DownloadVideo(ctx context.Context, in *DownloadVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VideoChunk], error)
}

type dataClient struct {
	cc grpc.ClientConnInterface
}

func NewDataClient(cc grpc.ClientConnInterface) DataClient {
	return &dataClient{cc}
}

func (c *dataClient) UploadVideo(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[VideoChunk, UploadStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Data_ServiceDesc.Streams[0], Data_UploadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VideoChunk, UploadStatus]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Data_UploadVideoClient = grpc.ClientStreamingClient[VideoChunk, UploadStatus]

func (c *dataClient) EstablishUploadConnection(ctx context.Context, in *VideoUploadData, opts ...grpc.CallOption) (*UploadStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadStatus)
	err := c.cc.Invoke(ctx, Data_EstablishUploadConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataClient) DownloadVideo(ctx context.Context, in *DownloadVideoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VideoChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Data_ServiceDesc.Streams[1], Data_DownloadVideo_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadVideoRequest, VideoChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Data_DownloadVideoClient = grpc.ServerStreamingClient[VideoChunk]

// DataServer is the server API for Data service.
// All implementations must embed UnimplementedDataServer
// for forward compatibility.
type DataServer interface {
	UploadVideo(grpc.ClientStreamingServer[VideoChunk, UploadStatus]) error
	EstablishUploadConnection(context.Context, *VideoUploadData) (*UploadStatus, error)
	DownloadVideo(*DownloadVideoRequest, grpc.ServerStreamingServer[VideoChunk]) error
	mustEmbedUnimplementedDataServer()
}

// UnimplementedDataServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServer struct{}

func (UnimplementedDataServer) UploadVideo(grpc.ClientStreamingServer[VideoChunk, UploadStatus]) error {
	return status.Errorf(codes.Unimplemented, "method UploadVideo not implemented")
}
func (UnimplementedDataServer) EstablishUploadConnection(context.Context, *VideoUploadData) (*UploadStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstablishUploadConnection not implemented")
}
func (UnimplementedDataServer) DownloadVideo(*DownloadVideoRequest, grpc.ServerStreamingServer[VideoChunk]) error {
	return status.Errorf(codes.Unimplemented, "method DownloadVideo not implemented")
}
func (UnimplementedDataServer) mustEmbedUnimplementedDataServer() {}
func (UnimplementedDataServer) testEmbeddedByValue()              {}

// UnsafeDataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServer will
// result in compilation errors.
type UnsafeDataServer interface {
	mustEmbedUnimplementedDataServer()
}

func RegisterDataServer(s grpc.ServiceRegistrar, srv DataServer) {
	// If the following call pancis, it indicates UnimplementedDataServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Data_ServiceDesc, srv)
}

func _Data_UploadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServer).UploadVideo(&grpc.GenericServerStream[VideoChunk, UploadStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Data_UploadVideoServer = grpc.ClientStreamingServer[VideoChunk, UploadStatus]

func _Data_EstablishUploadConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VideoUploadData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataServer).EstablishUploadConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Data_EstablishUploadConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataServer).EstablishUploadConnection(ctx, req.(*VideoUploadData))
	}
	return interceptor(ctx, in, info, handler)
}

func _Data_DownloadVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadVideoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataServer).DownloadVideo(m, &grpc.GenericServerStream[DownloadVideoRequest, VideoChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Data_DownloadVideoServer = grpc.ServerStreamingServer[VideoChunk]

// Data_ServiceDesc is the grpc.ServiceDesc for Data service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Data_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "video.Data",
	HandlerType: (*DataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstablishUploadConnection",
			Handler:    _Data_EstablishUploadConnection_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadVideo",
			Handler:       _Data_UploadVideo_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadVideo",
			Handler:       _Data_DownloadVideo_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "data.proto",
}
